
package mktstall;


import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;


public class SettingsDialog extends javax.swing.JDialog {
    //private Object fileChooserInputDir;
    private final JFileChooser fileChooserImageDir = new JFileChooser();
    private final JFileChooser fileChooserHoldingDir = new JFileChooser();
    private final JFileChooser fileChooserInputDir = new JFileChooser();
    private final JFileChooser fileChooserOutputDir = new JFileChooser();
    private final JFileChooser fileChooserTemporaryDir = new JFileChooser();
    private final JFileChooser fileChooserResourcesDir = new JFileChooser();
    private final JFileChooser fileChooserPythonExecutable = new JFileChooser();
    private final JFileChooser fileChooserMktStallPath = new JFileChooser();
    private final JFileChooser fileChooserMaxThreads = new JFileChooser();
    
    private Object outputdirectory;
    private final Settings settings;
    
    
    /**
     * Creates new form SetUpJDialog
     * @param parent
     * @param modal
     * @param settings
     */
    public SettingsDialog(JFrame parent, boolean modal, Settings settings) {
        
        super(parent, modal);
        initComponents();
        initComponentsTwo();
        this.settings = settings;
    }
    public final void initComponentsTwo(){
        this.setTitle("MktStall Settings");
        
    }
    
    public void loadSettings(){
        this.setImagePathDir(this.settings.getIMAGE_DIR());
        this.setHoldingPathDir(this.settings.getHOLDING_DIR());
        this.setInputDir(this.settings.getINPUT_DIR());
        this.setOutputDir(this.settings.getOUTPUT_DIR());
        this.setTemporaryDir(this.settings.getTEMP_DIR());
        this.setResourcesDir(this.settings.getRESOURCES_DIR());
        this.setPythonExecutableDir(this.settings.getPYTHON_PATH());
        this.setMktStallPathDir(this.settings.getMKTSTALL_PYTHON());
        this.setMaxThreads(this.settings.getMAX_THREADS());
    }
    
    private void setImagePathDir(String imagePathDirUserInput){
        ImageDirectoryTextField.setText(imagePathDirUserInput);
    }
    private void setHoldingPathDir(String holdingPathDirUserInput){
        holdingDirPathTextField.setText(holdingPathDirUserInput);
    }
    /**
     * Sets the input directory for images.
     * @param inputDirUserInput path to the image directory.
     */
    private void setInputDir(String inputDirUserInput){
        InputDirectoryTextField.setText(inputDirUserInput);    
    }
    private void setOutputDir(String outputDirUserInput){
        OutputDirectoryTextField.setText(outputDirUserInput);
    }
    private void setTemporaryDir(String temporaryDirUserInput){
        TemporaryDirectoryTextField.setText(temporaryDirUserInput);
    }
    private void setResourcesDir(String resourcesDirUserInput){
        ResourcesDirectoryTextField.setText(resourcesDirUserInput);
    }
    private void setPythonExecutableDir(String pythonExecutableDirUserInput){
        PythonExecutableTextField.setText(pythonExecutableDirUserInput);
    }
    private void setMktStallPathDir(String mktstallPathDirUserInput){
        MktStallPathTextField.setText(mktstallPathDirUserInput);
    }
    private void setMaxThreads(int maxThreadInput){
        MaxThreadsSpinner.setValue(maxThreadInput);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputDirectoryLabel = new java.awt.Label();
        InputDirectoryTextField = new java.awt.TextField();
        InputDirectoryButton = new java.awt.Button();
        OutputDirectoryLabel = new java.awt.Label();
        OutputDirectoryTextField = new java.awt.TextField();
        OutputDirectoryButton = new java.awt.Button();
        TemporaryDirectoryLabel = new java.awt.Label();
        TemporaryDirectoryTextField = new java.awt.TextField();
        TemporaryDirectoryButton = new java.awt.Button();
        ResourcesDirectoryLabel = new java.awt.Label();
        ResourcesDirectoryTextField = new java.awt.TextField();
        ResourcesDirectoryButton = new java.awt.Button();
        PythonExecutableLabel = new java.awt.Label();
        PythonExecutableTextField = new java.awt.TextField();
        PythonExecutableButton = new java.awt.Button();
        MktStallPathLabel = new java.awt.Label();
        MktStallPathTextField = new java.awt.TextField();
        MktStallPathButton = new java.awt.Button();
        MaxThreadsLabel = new java.awt.Label();
        OKButton = new java.awt.Button();
        CancelButton = new java.awt.Button();
        MaxThreadsSpinner = new javax.swing.JSpinner();
        button1 = new java.awt.Button();
        holdingDirPathTextField = new java.awt.TextField();
        label1 = new java.awt.Label();
        ImageDirectoryTextField = new java.awt.TextField();
        label2 = new java.awt.Label();
        HoldingDirectoryButton = new java.awt.Button();
        ImageDirectoryButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        InputDirectoryLabel.setText("Input Directory - path to inputs to mktstall_py");

        InputDirectoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDirectoryTextFieldActionPerformed(evt);
            }
        });
        InputDirectoryTextField.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                InputDirectoryTextFieldTextValueChanged(evt);
            }
        });

        InputDirectoryButton.setLabel("...");
        InputDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDirectoryButtonActionPerformed(evt);
            }
        });

        OutputDirectoryLabel.setText("Output Directory - path to results");

        OutputDirectoryTextField.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                OutputDirectoryTextFieldTextValueChanged(evt);
            }
        });

        OutputDirectoryButton.setLabel("...");
        OutputDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputDirectoryButtonActionPerformed(evt);
            }
        });

        TemporaryDirectoryLabel.setText("Temporary Directory - path to intermediate files");

        TemporaryDirectoryTextField.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                TemporaryDirectoryTextFieldTextValueChanged(evt);
            }
        });

        TemporaryDirectoryButton.setLabel("...");
        TemporaryDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemporaryDirectoryButtonActionPerformed(evt);
            }
        });

        ResourcesDirectoryLabel.setText("Resources Directory - path to MktStall resources");

        ResourcesDirectoryTextField.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                ResourcesDirectoryTextFieldTextValueChanged(evt);
            }
        });

        ResourcesDirectoryButton.setLabel("...");
        ResourcesDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResourcesDirectoryButtonActionPerformed(evt);
            }
        });

        PythonExecutableLabel.setText("Python Executable - path to Python");

        PythonExecutableTextField.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                PythonExecutableTextFieldTextValueChanged(evt);
            }
        });

        PythonExecutableButton.setLabel("...");
        PythonExecutableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PythonExecutableButtonActionPerformed(evt);
            }
        });

        MktStallPathLabel.setText("MktStall path - path to mktstall.py");

        MktStallPathTextField.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                MktStallPathTextFieldTextValueChanged(evt);
            }
        });

        MktStallPathButton.setLabel("...");
        MktStallPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MktStallPathButtonActionPerformed(evt);
            }
        });

        MaxThreadsLabel.setText("Maximum number of threads");

        OKButton.setLabel("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setLabel("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        MaxThreadsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        button1.setLabel("Defaults");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        label1.setText("Holding Directory - path to empty holding directory");

        label2.setText("Image Directory - path to directory containing images");

        HoldingDirectoryButton.setLabel("...");
        HoldingDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoldingDirectoryButtonActionPerformed(evt);
            }
        });

        ImageDirectoryButton.setLabel("...");
        ImageDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageDirectoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InputDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PythonExecutableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OutputDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TemporaryDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResourcesDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MktStallPathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(MaxThreadsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(MktStallPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MktStallPathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PythonExecutableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PythonExecutableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ResourcesDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResourcesDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TemporaryDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TemporaryDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(OutputDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(OutputDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(InputDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(InputDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(MaxThreadsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ImageDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImageDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(holdingDirPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoldingDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImageDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ImageDirectoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HoldingDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(holdingDirPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(InputDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(InputDirectoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OutputDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OutputDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(OutputDirectoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TemporaryDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TemporaryDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(TemporaryDirectoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(ResourcesDirectoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ResourcesDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ResourcesDirectoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PythonExecutableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PythonExecutableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(PythonExecutableTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MktStallPathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MktStallPathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(MktStallPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaxThreadsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(MaxThreadsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.loadSettings();
        this.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void InputDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDirectoryButtonActionPerformed
        //lauch jfile chooser
        int returnInputDir = fileChooserInputDir.showOpenDialog(this);
        if (returnInputDir == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening input file");
            File inputdir = fileChooserInputDir.getSelectedFile();
            String inputpath = inputdir.getAbsolutePath();
            //OutputDirectoryTextField.read(new FileReader( outputdir.getAbsolutePath() ), null );
            InputDirectoryTextField.setText(inputpath);
        }
    }//GEN-LAST:event_InputDirectoryButtonActionPerformed

    private void OutputDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputDirectoryButtonActionPerformed
        //lauch file chooser
        int returnOutputDir = fileChooserOutputDir.showOpenDialog(this);
        if (returnOutputDir == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening output file");
            File outputdir = fileChooserOutputDir.getSelectedFile();
            String outputpath = outputdir.getAbsolutePath();
            OutputDirectoryTextField.setText(outputpath);
        }
    }//GEN-LAST:event_OutputDirectoryButtonActionPerformed

    private void TemporaryDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemporaryDirectoryButtonActionPerformed
        //launch file chooser
        int returnTemporaryDir = fileChooserTemporaryDir.showOpenDialog(this);
        if (returnTemporaryDir == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening temporary file");
            File temporarydir = fileChooserTemporaryDir.getSelectedFile();
            String temporarypath = temporarydir.getAbsolutePath();
            TemporaryDirectoryTextField.setText(temporarypath);
        }
    }//GEN-LAST:event_TemporaryDirectoryButtonActionPerformed

    private void ResourcesDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResourcesDirectoryButtonActionPerformed
        //launch file chooser
        int returnResourcesDir = fileChooserResourcesDir.showOpenDialog(this);
        if (returnResourcesDir == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening resources dir file");
            File temporarydir = fileChooserResourcesDir.getSelectedFile();
            String temporarypath = temporarydir.getAbsolutePath();
            ResourcesDirectoryTextField.setText(temporarypath);
        }
    }//GEN-LAST:event_ResourcesDirectoryButtonActionPerformed

    private void PythonExecutableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PythonExecutableButtonActionPerformed
        //launch file chooser
        int returnPythonExecutable = fileChooserPythonExecutable.showOpenDialog(this);
        if (returnPythonExecutable == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening python exe dir file");
            File pythonexedir = fileChooserPythonExecutable.getSelectedFile();
            String pythonexepath = pythonexedir.getAbsolutePath();
            PythonExecutableTextField.setText(pythonexepath);
        }
    }//GEN-LAST:event_PythonExecutableButtonActionPerformed

    private void MktStallPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MktStallPathButtonActionPerformed
        int returnMktStallPath = fileChooserMktStallPath.showOpenDialog(this);
        if (returnMktStallPath == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening mktstall path");
            File mktstallpathdir = fileChooserMktStallPath.getSelectedFile();
            String mktstallpath = mktstallpathdir.getAbsolutePath();
            MktStallPathTextField.setText(mktstallpath);
        }
    }//GEN-LAST:event_MktStallPathButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed

        this.settings.updateSettings(Settings.Setting.IMAGE_DIR, this.ImageDirectoryTextField.getText());
        this.settings.updateSettings(Settings.Setting.HOLDING_DIR, this.holdingDirPathTextField.getText());
        this.settings.updateSettings(Settings.Setting.INPUT_DIR, this.InputDirectoryTextField.getText());
        this.settings.updateSettings(Settings.Setting.MKTSTALL_PYTHON, this.MktStallPathTextField.getText());
        this.settings.updateSettings(Settings.Setting.OUTPUT_DIR, this.OutputDirectoryTextField.getText());
        this.settings.updateSettings(Settings.Setting.PYTHON_PATH, this.PythonExecutableTextField.getText());
        this.settings.updateSettings(Settings.Setting.RESOURCES_DIR, this.ResourcesDirectoryTextField.getText());
        this.settings.updateSettings(Settings.Setting.TEMP_DIR, this.TemporaryDirectoryTextField.getText());
        this.settings.updateSettings(Settings.Setting.MAX_THREADS, (Integer) this.MaxThreadsSpinner.getValue());
        this.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed

    @Override
    public void setVisible(boolean visible){
        if(true){
            this.loadSettings();
        }
        super.setVisible(visible);
    }
    private void InputDirectoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDirectoryTextFieldActionPerformed
        
    }//GEN-LAST:event_InputDirectoryTextFieldActionPerformed

    private void InputDirectoryTextFieldTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_InputDirectoryTextFieldTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDirectoryTextFieldTextValueChanged

    private void OutputDirectoryTextFieldTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_OutputDirectoryTextFieldTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_OutputDirectoryTextFieldTextValueChanged

    private void TemporaryDirectoryTextFieldTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_TemporaryDirectoryTextFieldTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TemporaryDirectoryTextFieldTextValueChanged

    private void ResourcesDirectoryTextFieldTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_ResourcesDirectoryTextFieldTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ResourcesDirectoryTextFieldTextValueChanged

    private void PythonExecutableTextFieldTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_PythonExecutableTextFieldTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PythonExecutableTextFieldTextValueChanged

    private void MktStallPathTextFieldTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_MktStallPathTextFieldTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_MktStallPathTextFieldTextValueChanged

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        settings.loadSettingsConfig();
        this.loadSettings();
    }//GEN-LAST:event_button1ActionPerformed

    private void ImageDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageDirectoryButtonActionPerformed
        int imageDirectoryPath = fileChooserMktStallPath.showOpenDialog(this);
        if (imageDirectoryPath == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening image directory path");
            File imagepathdir = fileChooserMktStallPath.getSelectedFile();
            String imagepath = imagepathdir.getAbsolutePath();
            this.ImageDirectoryTextField.setText(imagepath);
        }
    }//GEN-LAST:event_ImageDirectoryButtonActionPerformed

    private void HoldingDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoldingDirectoryButtonActionPerformed
        int holdingDirectoryPath = fileChooserMktStallPath.showOpenDialog(this);
        if (holdingDirectoryPath == JFileChooser.APPROVE_OPTION) {
            System.out.println("opening holding directory path");
            File holdingpathdir = fileChooserMktStallPath.getSelectedFile();
            String holdingpath = holdingpathdir.getAbsolutePath();
            this.ImageDirectoryTextField.setText(holdingpath);
        }
    }//GEN-LAST:event_HoldingDirectoryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button CancelButton;
    private java.awt.Button HoldingDirectoryButton;
    private java.awt.Button ImageDirectoryButton;
    private java.awt.TextField ImageDirectoryTextField;
    private java.awt.Button InputDirectoryButton;
    private java.awt.Label InputDirectoryLabel;
    private java.awt.TextField InputDirectoryTextField;
    private java.awt.Label MaxThreadsLabel;
    private javax.swing.JSpinner MaxThreadsSpinner;
    private java.awt.Button MktStallPathButton;
    private java.awt.Label MktStallPathLabel;
    private java.awt.TextField MktStallPathTextField;
    private java.awt.Button OKButton;
    private java.awt.Button OutputDirectoryButton;
    private java.awt.Label OutputDirectoryLabel;
    private java.awt.TextField OutputDirectoryTextField;
    private java.awt.Button PythonExecutableButton;
    private java.awt.Label PythonExecutableLabel;
    private java.awt.TextField PythonExecutableTextField;
    private java.awt.Button ResourcesDirectoryButton;
    private java.awt.Label ResourcesDirectoryLabel;
    private java.awt.TextField ResourcesDirectoryTextField;
    private java.awt.Button TemporaryDirectoryButton;
    private java.awt.Label TemporaryDirectoryLabel;
    private java.awt.TextField TemporaryDirectoryTextField;
    private java.awt.Button button1;
    private java.awt.TextField holdingDirPathTextField;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
